### ISSUE TITLE
Add source support

### ISSUE THREAD

**Issue by tkurki** [tkurki/signalk-to-influxdb#14]
PLugin should support distinguishing data on `$source`, not just SK  path.

**Comment by edefalque** [comment]
Plugin writes the source of data to InfluxDB. However the plugin writes a value for a path every sampling period (Resolution parameter) irrespective of the source; only the data associated to one source will be written every sampling period and a "fast" source will be written more often than a "slow" one. Hence, when charting 2 sources separately from InfluxDB data, the plot line of the "fast" source will alternate with the plot line of the other source and the fast source line segments will be longer than the slow source line segments. Ideally the plugin should write the last known value of every path/source every sampling period.

**Comment by tkurki** [comment]
Agree on all points. Not sure if this can be implemented in a backwards compatible way, but if not then it is what it is.

**Comment by edefalque** [comment]
Thanks Teppo,
No big deal for me.
Just wanted to comment.
Not competent enough to suggest any code change.
Etienne

**Comment by tkurki** [comment]
See #43. Closing, as sourceId is already stored as Influx tag `source`.
