### ISSUE TITLE
Failed to connect to localhost port 8086

### ISSUE THREAD

**Issue by Jamos1988** [tkurki/signalk-to-influxdb#35]
Hi! Thanks for the great work! I have just installed your plug-in into Signal-K and have configured it as follows:

Host: localhost
Port: 8086
Database: (empty)

In terminal I get the following error when trying to create the database:

pi@openplotter:~ $ curl -X POST http://localhost:8086/query?q=CREATE+DATABASE+boatdata
curl: (7) Failed to connect to localhost port 8086: Connection refused

I have also installad Grafana and I am trying to configure the connection, in there I receive the error:
Network Error: Bad Gateway(502)

I think the port is not starting, what could I do to fix this?

**Comment by tkurki** [comment]
Have you installed influxdb? It seems to be missing, either not installed or not started.

**Comment by Jamos1988** [comment]
Thanks, indeed I have not. Thought the plug-in was enough. Would this instruction be ok? http://blog.centurio.net/2018/10/28/howto-install-influxdb-and-grafana-on-a-raspberry-pi-3/

**Comment by tkurki** [comment]
Yes
