### ISSUE TITLE
Split navigation.position geojson into separate measurements

### ISSUE THREAD

**Issue by barney2074** [tkurki/signalk-to-influxdb#37]
Hi Teppo

Many thanks for this- I'm having a lot of fun with Signalk/Influx/Grafana

I was wondering if is possible to split the navigation.position geojson array into separate longitude and latitude measurements or columns?
Reason being- some of the Grafana panels require separate long/lat values.

I've had a look on the Influx/Grafana end & can't see an obvious way to do this (possibly a flux script?)

i.e something like:
                    "name": "navigation.position",
                    "columns": [
                        "time",
                        "context",
                        "longitude",
                        "latitude",
                        "source"
                    ],
                    "values": [
                        [
                            "2020-02-22T01:01:26.961Z",
                            "vessels.urn:mrn:imo:mmsi:503063560",
                            "151.3048064",
                            "-33.65744",
                            "OPcan.1"
                        ]

thanks

Andrew

**Comment by tkurki** [comment]
I've bumped into this issue myself. One solution would be to provide a configuration option in the plugin that would write the coordinates as two separate numeric values. Not sure how that would play with the snapshot and history playback features that this plugin provides. Also if you have a lot of data you

I haven't used flux, so can't help you there without going to the trouble of learning more details. Maybe there would be a way to create two separate rollup series (can't recall what the exact InfluxDb term is...) to split the data in Inlfux.

I've been working on a third option: 
- the plugin providing a Signal K native API to fetch the values
- a Grafana Signal K datasource to fetch the data via the API
- a Grafana trackmap panel to display the data

The Grafana parts are at https://github.com/tkurki/signalk-grafana/pull/1 and the plugin part here https://github.com/tkurki/signalk-to-influxdb/pull/34, but as evident the work stalled a while ago.

**Comment by barney2074** [comment]
Hi Teppo,

thanks.
I did have a play around with a Flux query- it seems possible- but using string functions is not very efficient. The Flux queries also seem to be way too much for a little PI- it runs at 100% for several seconds just for a single query.- whereas using the older connection method is is ticking over at 5% even with a Grafana chart refreshing every second

[Flux query](https://dconstructors-my.sharepoint.com/:i:/p/andrew/EX-Ejs_yV2lMqDHHHsqhmloBrI0cavyVM2RWUiuuL2aUBQ?e=kJzWG7)

[Live chart](https://dconstructors-my.sharepoint.com/:v:/p/andrew/EQ0KzPkw1PZHrQ0arMui97kB44w7mmTkA-iAFFTwlOicUw?e=vhVoOa)

I think the best solution is probably a Grafana map panel that accepts the geojson- but for now, the Grafana charts are ok


Andrew

**Comment by tkurki** [comment]
#39 added the possibility to store coordinates as separate measurements.

**Comment by barney2074** [comment]
thanks for this Teppo
