### ISSUE TITLE
timestamp sent to influx uses incorrect timezone

### ISSUE THREAD

**Issue by kreucher** [tkurki/signalk-to-influxdb#47]
hi! thanks for the great plugin!

i noticed data in influx has timestamps roughly +7 hours in the future. my localtime is -0700 so figured it was a timezone issue:
```
$ influx -database goldenmean -execute 'select last(*) from "electrical.batteries.1.voltage"' && date +%s%N
name: electrical.batteries.1.voltage
time                last_value
----                ----------
1596060830085000000 11.57       <-- influx timestamp: Wed Jul 29 2020 15:13:50
1596035635156144036             <-- real epoch:       Wed Jul 29 2020 08:13:55
```

looking at the code, update.timestamp from signalk appears to be a UTC string, but without any timezone indicator:
```
2020-07-29T15:25:28.695
```

in `skToInflux.js:51`, the timestamp is converted to a Date with `new Date(update.timestamp)` but Date is interpreting this as localtime:
```
d = new Date('2020-07-29T15:25:28.695');
Wed Jul 29 2020 15:25:28 GMT-0700 (Pacific Daylight Time)   <-- in the future
```

Adding in a `Z` at the end of the string timestamp does the trick, as Date interprets this as UTC:
```
d = new Date('2020-07-29T15:25:28.695Z');
Wed Jul 29 2020 08:25:28 GMT-0700 (Pacific Daylight Time)   <-- correct!
```

i changed `skToInflux.js:51` to `new Date(update.timestamp + 'Z')` and influx has the correct timestamp now:
```
$ influx -database goldenmean -execute 'select last(*) from "electrical.batteries.1.voltage"' && date +%s%N
name: electrical.batteries.1.voltage
time                last_value
----                ----------
1596038643098000000 11.56       <-- influx timestamp: Wed Jul 29 2020 09:04:03
1596038651677254700             <-- real epoch:       Wed Jul 29 2020 09:04:11
```

note i'm just getting starting using signalk so not actually sure if this is a signalk-to-influxdb or signalk bug. not sure where update.timestamp is coming from, and if signalk, should it be encoding the Z to indicate UTC?

**Comment by tkurki** [comment]
Where is your data coming from?

**Comment by kreucher** [comment]
i tried two sources... one was NMEA via network and then i tried NMEA 2k via can0 (a canable.io) -- source for me didn't matter, both had this issue.

**Comment by tkurki** [comment]
Thanks for reminding me about this, I'l try to find the time to have a look.

**Comment by tkurki** [comment]
I think this has been fixed on the sk server side. Please reopen if still relevant.
