### ISSUE TITLE
Include Depth value in Track data

### ISSUE THREAD

**Issue by panaaj** [tkurki/signalk-to-influxdb#50]
Is it possible the returned track data from `./self/track/` have depth values in included as "altitude' in the position data?

e.g. [6.3, 50.23, 12.5]

**Comment by tkurki** [comment]
It should then probably be negative?

Easy enough to add it as an option, but I am dreaming of having a comprehensive way to query any historical data with positions collated, not just depth.

**Comment by panaaj** [comment]
I thought that might be the case but figured that depth/altitude were an easy fit.
Makes colour by depth a reality in Freeboard

**Comment by tkurki** [comment]
The plugin now includes a way to query the db for arbitrary data, so I don't think this direction is worth exploring.
