### ISSUE TITLE
Running in Docker - No host available/Request timed out

### ISSUE THREAD

**Issue by pbegg** [tkurki/signalk-to-influxdb#51]
I am unsure if this is an issue from running with docker or with the plugin. After the server has been running for a few minutes I end up with the following in the log:

Nov 05 22:26:24 signalk-to-influxdb:Error: No host available
Nov 05 22:26:34 signalk-to-influxdb:Error: Request timed out

Has anyone else come across this and a potential fix?

I have tried with docker versions:
1.35.1
v1.36.0-beta.3

I have the batch interval set to 10s. Watching grafana load the data with auto refresh every 10s it starts loading with the grafana dash loading every 10 seconds then slowly gets delayed, it is updating the data but everytime it gets delayed by an extra 5-10 seconds until after ~5mins the errors appear in singalk debug log.

**Comment by tkurki** [comment]
Do you have both SK server and Influx running under grafana?

What have you configured as the Influxdb host?

What platform (computer) is this on?

If you try accessing the influxdb from the command line does it respond?

If you disable Grafana does this still happen?

What version of Influx? Anything in Influxdb log?

For reference I've been running SK, Influxdb and Grafana for two season with no glitches under docker-compose with https://github.com/tkurki/marinepi-provisioning/blob/master/roles/signalk-docker/templates/docker-compose.j2

**Comment by KEGustafsson** [comment]
Try to set Grafana refresh rate slower, e.g. 1/min. If you have many Grafana queries to Influxdb, it will load Influxdb heavily.

I have been also running SK, Influxdb and Grafana in docker compose without any problems.

**Comment by phil28aus** [comment]
Thanks guys,

I haven't had a chance to look at it again yet but hopefully this coming week and I will post what I find

**Comment by pbegg** [comment]
I think this was an issue with the hardware I was using. Running on a RPi4 now with no issues all running under docker.
