### ISSUE TITLE
Add Blacklist or Whitelist via batch or file

### ISSUE THREAD

**Issue by jere-marshall** [tkurki/signalk-to-influxdb#53]
It would be convenient if we could create a blacklist or whitelist using a file rather than entering path names individually.

**Comment by virtuvas** [comment]
...and to add to that, it would also be helpful to enable the use of wildcards:

notifications.propulsion.port.*
instead of listing the 24 or so notifications you don't want to pass over to influxdb.

V.

**Comment by tkurki** [comment]
You can edit the settings file under SK settings directory manually and restart the server to get it to pick changes up.

Wildcard makes sense, but please create a separate issue for it.
