### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by Jamos1988** [tkurki/signalk-to-influxdb#54]
Hi,

I have the following settings: 

![image](https://user-images.githubusercontent.com/59844840/129889137-95b3e9c2-494f-4c41-a541-448c32ae1e81.png)

And it has been working perfectly for weeks, however there is now high CPU load. One of the cores is running over 100%.
So, I've been doing some checking.

DB sizes:

![image](https://user-images.githubusercontent.com/59844840/129889251-9bbb7f30-1806-44c1-a1bf-a28d6ae811b6.png)

And tried to disable monitoring in influxdb.conf:

![image](https://user-images.githubusercontent.com/59844840/129889375-2b67b087-4f0d-4cd9-adb8-cae23c792025.png)

This did not yet fix the high CPU issue yet. I am thinking of applying a data retention period so nothing gets stored older than 1 month. But, I don't know how to do that. Someone in the slack channel said it could be done by using chronograf, but although it is installed and running on my openplotter I cannot access it on port 8889.

I was wondering if you might have some advice. The high CPU usage makes the system unusable.

Kind regards,

Jamos

**Comment by tkurki** [comment]
What process is the one with high CPU usage?

If yes you might want to raise the issue in some influxdb focused forum.

I have not set up data retention on my boat.

**Comment by Jamos1988** [comment]
Ok, I understand. May I report just one test I made? Maybe you have some other ideas.

I just did a test, disabling the influxdb signalk plugin and disabling Grafana, to see if Influxdb remains stable just by it self. My idea was if no read or writes are performed, influxdb should behave fine right? It does not, still above 100% CPU... weird huh?

**Comment by tkurki** [comment]
So this is about Influx being stuck in some housekeeping task. I think somebody mentioned smthing similar in Slack? Anyway, even more a reason to turn to Influx specific forums.

We can leave this issue open for a while, if you want to document your progress for posterity.

**Comment by Jamos1988** [comment]
Ok I decided to re-install influxdb, chronograf and telegraf. It is now working on port 8889. I dropped the previous databases by using DROP DATABASE "database_name" and decided to start over again. Now, using chronograf I have enabled a retention policy of 4 weeks: 
![image](https://user-images.githubusercontent.com/59844840/130035911-c20ce573-43f8-4249-bb7f-30b7f6891f35.png)
