### ISSUE TITLE
Separate influx/grafana paths when SK path has >1 source

### ISSUE THREAD

**Issue by htool** [tkurki/signalk-to-influxdb#56]
Hi,

I've got a homemade magnetic compass next to my Raymarine Fluxgate one and I'd like to graph both comparison. Both sources end up in SK, but end up in 1 grafana path.

Ideally I'd like to preserve both and have e.g. navigation.headingMagnetic_$src as well.

**Comment by tkurki** [comment]
All measurements written into Influxdb are tagged with `context` (the vessel id) and `source` (the source of the data). Just use the source in your query like so 

![image](https://user-images.githubusercontent.com/1049678/146427373-195d9544-2ea2-4dfe-9def-372b291f8ab7.png)

the autocomplete shows you what sources are available, albeit not per path, just the global set of source values I think.
