### ISSUE TITLE
Add Can Name as a Tag to the Influx Series, not just Source

### ISSUE THREAD

**Issue by markfarnan** [tkurki/signalk-to-influxdb#58]
**Problem:** 
Currently InfluxDB series are created with the Source to uniquely seperate series, however source can, and does change between network reboots, especially if there are other changes in the network.

navigation.position,context=vessels.urn:mrn:imo:mmsi:000000000,source=can0.115
navigation.position,context=vessels.urn:mrn:imo:mmsi:000000000,source=can0.43

This can cause a horribly mish-mash of series and knock on effects, especially in dashboards.  

The issue shows up most with navigation.position as there are often multiple sources of this on the boat, and more and more things integrate a GPS. 

**Proposed Solution:**

Replace source with CanName, or other unique identifier to the taglist in Influx,  so that they can be uniquely identified regardless of network address.   This is required when displays, dashboards etc need to filter and display a specific value from a specific sensor,  without having to edit dashboards if Source changes.

**Comment by tkurki** [comment]
oops. have you tried turning on `Use Can NAME in source data` in your N2K connection’s settings? Server => Data Connections => <your n2k connection>

**Comment by markfarnan** [comment]
Ok that works,   

Now Influx looks like this.  Much better thanks.    

navigation.position,context=vessels.urn:mrn:imo:mmsi:000000000,source=can0.c08c8c00e771dd27
navigation.position,context=vessels.urn:mrn:imo:mmsi:000000000,source=can0.c1321419e7672c91
