### ISSUE TITLE
What will be the measurement key in case of multiple values?

### ISSUE THREAD

**Issue by zikann** [tkurki/signalk-to-influxdb#59]
What will be the measurement key in case of multiple values for eg. first and second engine temp?
The case is described here thoroughly here: https://signalk.org/specification/1.5.0/doc/data_model_multiple_values.html 

>It is quite possible for a key value to come from more than one device. Many modern devices have a built in GPS receiver and as a result on any given boat there may be several sources of position, speed over ground, and heading. Multiple depth sounders are also common, often installed to port and starboard on monohull sailboats or in each hull of a catamaran.

SignalK enables subscription of this value by full path including source which looks like this:
`navigation.courseOverGroundTrue.values[n2k./dev/ikommunicate.128267]`

How will such data be saved in influxdb? Is this case somehow implemented?

Regards

**Comment by tkurki** [comment]
See #56.
