### ISSUE TITLE
"Latitude and Longitude as separate measurements to Influxdb" not working?

### ISSUE THREAD

**Issue by Krillle** [tkurki/signalk-to-influxdb#62]
The option "Latitude and Longitude as separate measurements to Influxdb" is checked, but I cant find any separate measurements in influx. Only `navigation.position`. What is the trick to get the values separately?

**Comment by tkurki** [comment]
![4C905FBD-D9E7-4EFD-A99D-2C70B9ABB31C](https://user-images.githubusercontent.com/1049678/171086449-0a54680e-f00f-4836-8998-f2941841d175.jpeg)

**Comment by Krillle** [comment]
Thank you.
